import { FC } from 'react'
import Head from 'next/head'

import MainCard from '../components/MainCard'

const Home: FC = () => {
  return (
    <>
      <Head>
        <title>Naufal Akbar Nugroho</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <MainCard />
      </main>
    </>
  )
}

export default Home
