import { FC } from 'react'
import Head from 'next/head'
import Card from '../components/Card'

const Home: FC = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Card />
      </main>
    </>
  )
}

export default Home
